[tool.poetry]
name = "poetry-req"
version = "0.1.0"
description = "Poetry requirements for goit hw8"
authors = ["eughappy <degai7454@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
